/**
 * GENERATED by scripts/photos-from-manifest.mjs — do not hand-edit; re-run it.
 *
 * Photographs keyed by menu item id, sourced from ott-demo-image-manifest.json.
 * `data/menu.ts` merges this in, so a photo reaches every place its dish appears
 * without the menu data itself ever changing. An item with no entry here renders
 * the designed placeholder, which is most of the menu and is meant to be.
 *
 * Mode: the restaurant's own CDN
 */

import type { FoodImage } from "@/lib/types";

export const photos: Record<string, FoodImage> = {
  "buford-blue": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-tx7utkfn1cff105yomcetn98n54j/fit%3Dcontain%2Cwidth%3D1040",
    alt: "All beef 6 oz patties, crumbled blue cheese, bacon-onion jam, tomato, pickle, onion & signature sauce",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "chocolate-chaos": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-q81kfr1x2xrhhyoc4hyfo20yvbjv/fit%3Dcontain%2Cwidth%3D1040",
    alt: "Soft chocolate cake layered with smooth chocolate frosting for a classic treat",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "cookie-monster": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-95k7r0y7jn28b2fc3ldnhkiqr9z5/fit%3Dcontain%2Cwidth%3D1040",
    alt: "Chocolate ice cream, chocolate syrup, cookie crumbles, whipped cream, and chocolate chips with a blue frosting rim",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "flaming-avalanche": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-aswmcz83ca06qjhicelqgp2wqdg1/fit%3Dcontain%2Cwidth%3D1040",
    alt: "All beef 6 oz. patties, pepper-jack cheese, Flamin' Hot Cheetos, scorpion glaze, pickle, onion, signature sauce, dipped in queso & Flamin' Hot Chee…",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "georgia-summer": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-tt24n2voq5b0zq1tlvlmw4fgnksr/fit%3Dcontain%2Cwidth%3D1040",
    alt: "All beef 6 oz. patties, peach-jalapeno chutney, pimento cheese, grilled onions, pickle, onion, & sig sauce",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "hog-wild": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-e7sj0p1du5xtv14g2kqmoesllvsa/fit%3Dcontain%2Cwidth%3D1040",
    alt: "Slow-smoked pulled pork piled on a toasted brioche bun, topped with house BBQ sauce, creamy coleslaw, and crunchy pickles",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "key-to-paradise": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-bufvjyds2tlgemd86pc0bjhgkxgr/fit%3Dcontain%2Cwidth%3D1040",
    alt: "Lime-infused vanilla ice cream, key lime pie, whipped cream, graham crackers, and a lime twist with a graham cracker-crusted rim",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "loaded-nachos": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-vgxqktoubo8xp6gq9oj5totgxo3y/fit%3Dcontain%2Cwidth%3D1040",
    alt: "A tower of crispy tortilla chips loaded with your choice of chicken or beef, topped with shredded lettuce, tomatoes, jalapeños, onions, shredded ch…",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "texas-chicken-rolls": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-st37rhz6jvweza1wgqy6cjmwte48/fit%3Dcontain%2Cwidth%3D1040",
    alt: "Egg rolls packed with tender grilled chicken, black beans, corn bell peppers, spinach, & a blend of melted cheeses",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "the-big-catch": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-dilhh0tsau36tjze1j1irvznhpbw/fit%3Dcontain%2Cwidth%3D1040",
    alt: "A perfectly seasoned, crisp salmon fillet nestled in a toasted bun, topped with fresh greens, cucumber, red onion & finished with a creamy dill ran…",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "the-hangover": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-5vguszywcanpclvqn1ylde8oqbfm/fit%3Dcontain%2Cwidth%3D1040",
    alt: "All beef 6 oz. patties on a sugar waffle, candy peppered bacon, American cheese, fried egg, hash brown, maple syrup & top it off with a dusting of…",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
  "the-samplers": {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-9eynsmyid272pffixb29dwwqxq4k/fit%3Dcontain%2Cwidth%3D1040",
    alt: "Best of all worlds: wings, jalapeño poppers, fried mozzarella, and Texas chicken rolls",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
  },
};

/** The full-bleed photograph behind the homepage headline. */
export const heroPhoto: FoodImage | null = {
    src: "https://imagedelivery.net/aPDHOWLzkdlEAMvg3YLQug/production-aswmcz83ca06qjhicelqgp2wqdg1/fit%3Dcontain%2Cwidth%3D1040",
    alt: "All beef 6 oz. patties, pepper-jack cheese, Flamin' Hot Cheetos, scorpion glaze, pickle, onion, signature sauce, dipped in queso & Flamin' Hot Chee…",
    focal: "50% 50%",
    credit: "Restaurant's own photography, served from their CDN",
};
