'use strict';

const END_OF_CALL_REPORT = 'end-of-call-report';
const STATUS_UPDATE = 'status-update';

/**
 * A call is finished when either the end-of-call report lands or a status
 * update says "ended". Both are accepted because end-of-call-report is not
 * guaranteed to arrive; duplicate work is harmless since delivery dedupes on
 * the call id.
 */
function isCallCompleteEvent(event) {
  if (!event) return false;
  if (event.type === END_OF_CALL_REPORT) return true;
  return event.type === STATUS_UPDATE && event.status === 'ended';
}

function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function firstString(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim()) return value.trim();
  }
  return null;
}

function toIsoTimestamp(value) {
  if (typeof value === 'number' && Number.isFinite(value)) {
    const date = new Date(value);
    return Number.isNaN(date.getTime()) ? null : date.toISOString();
  }
  if (typeof value === 'string' && value.trim()) {
    const date = new Date(value);
    return Number.isNaN(date.getTime()) ? null : date.toISOString();
  }
  return null;
}

/**
 * Every Vapi server message for an assistant arrives at the same Server URL,
 * wrapped as { message: { type, ... } }. This turns one into a flat, trusted
 * shape or explains why it couldn't.
 */
function parseVapiEvent(body) {
  if (!isPlainObject(body)) {
    return { ok: false, reason: 'body_not_object' };
  }

  // Vapi wraps events in `message`; tolerate an unwrapped body defensively.
  const message = isPlainObject(body.message) ? body.message : body;
  const type = typeof message.type === 'string' ? message.type : null;
  if (!type) {
    return { ok: false, reason: 'missing_message_type' };
  }

  const call = isPlainObject(message.call) ? message.call : {};
  const artifact = isPlainObject(message.artifact) ? message.artifact : {};
  const callArtifact = isPlainObject(call.artifact) ? call.artifact : {};

  const structuredOutputs = isPlainObject(artifact.structuredOutputs)
    ? artifact.structuredOutputs
    : isPlainObject(callArtifact.structuredOutputs)
      ? callArtifact.structuredOutputs
      : null;

  return {
    ok: true,
    event: {
      type,
      status: firstString(message.status, call.status),
      callId: firstString(call.id, message.callId),
      assistantId: firstString(
        call.assistantId,
        isPlainObject(message.assistant) ? message.assistant.id : null,
      ),
      endedReason: firstString(message.endedReason, call.endedReason),
      endedAt: toIsoTimestamp(call.endedAt || message.timestamp || null),
      structuredOutputs,
    },
  };
}

/**
 * Structured outputs are keyed by output id: { "<uuid>": { name, result } }.
 * Match on the configured name rather than a hardcoded id, since the id is
 * generated by Vapi and differs per environment.
 */
function findStructuredOutput(structuredOutputs, name) {
  if (!isPlainObject(structuredOutputs)) return null;

  for (const [key, value] of Object.entries(structuredOutputs)) {
    if (!isPlainObject(value)) continue;
    const outputName = typeof value.name === 'string' ? value.name : key;
    if (outputName !== name) continue;
    if (isPlainObject(value.result)) return value.result;
    // Tolerate a flattened variant where the value *is* the extracted result.
    if (!('result' in value) && key === name) return value;
    return null;
  }

  return null;
}

function structuredOutputNames(structuredOutputs) {
  if (!isPlainObject(structuredOutputs)) return [];
  return Object.entries(structuredOutputs).map(([key, value]) =>
    isPlainObject(value) && typeof value.name === 'string' ? value.name : key,
  );
}

module.exports = {
  END_OF_CALL_REPORT,
  STATUS_UPDATE,
  isCallCompleteEvent,
  parseVapiEvent,
  findStructuredOutput,
  structuredOutputNames,
  isPlainObject,
};
